In [ ]:
import numpy as np # linear algebra
import pandas as pd

In [ ]:
delivery=pd.read_csv('deliveries.csv')

In [ ]:
matches=pd.read_csv('matches.csv')

In [ ]:
matches.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [ ]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [ ]:
matches.isnull().sum()

id                   0
Season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               4
win_by_runs          0
win_by_wickets       0
player_of_match      4
venue                0
umpire1              2
umpire2              2
umpire3            637
dtype: int64

In [ ]:
delivery.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batsman                  0
non_striker              0
bowler                   0
is_super_over            0
wide_runs                0
bye_runs                 0
legbye_runs              0
noball_runs              0
penalty_runs             0
batsman_runs             0
extra_runs               0
total_runs               0
player_dismissed    170244
dismissal_kind      170244
fielder             172630
dtype: int64

In [ ]:
matches.duplicated().sum()

np.int64(0)

In [ ]:
delivery.duplicated().sum()

np.int64(23)

In [ ]:
delivery [delivery.duplicated()]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
52178,221,1,Mumbai Indians,Delhi Daredevils,4,1,SR Tendulkar,C Madan,PJ Sangwan,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
162805,7946,1,Rajasthan Royals,Royal Challengers Bangalore,4,4,AM Rahane,RA Tripathi,UT Yadav,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
162806,7946,1,Rajasthan Royals,Royal Challengers Bangalore,4,5,AM Rahane,RA Tripathi,UT Yadav,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
162870,7946,1,Rajasthan Royals,Royal Challengers Bangalore,13,5,RA Tripathi,AM Rahane,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
162964,7946,2,Royal Challengers Bangalore,Rajasthan Royals,10,1,AB de Villiers,Mandeep Singh,I Sodhi,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
166610,11144,2,Sunrisers Hyderabad,Rajasthan Royals,6,6,J Bairstow,DA Warner,J Archer,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
167990,11150,1,Royal Challengers Bangalore,Rajasthan Royals,10,1,PA Patel,S Hetmyer,K Gowtham,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
168080,11150,2,Rajasthan Royals,Royal Challengers Bangalore,4,4,JC Buttler,AM Rahane,N Saini,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
169404,11311,1,Royal Challengers Bangalore,Delhi Capitals,1,6,PA Patel,V Kohli,I Sharma,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
170110,11314,1,Kolkata Knight Riders,Chennai Super Kings,3,1,N Rana,RV Uthappa,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
170111,11314,1,Kolkata Knight Riders,Chennai Super Kings,3,2,N Rana,RV Uthappa,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
170117,11314,1,Kolkata Knight Riders,Chennai Super Kings,3,7,KD Karthik,RV Uthappa,DL Chahar,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
170119,11314,1,Kolkata Knight Riders,Chennai Super Kings,4,1,RV Uthappa,KD Karthik,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
170120,11314,1,Kolkata Knight Riders,Chennai Super Kings,4,1,RV Uthappa,KD Karthik,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
171685,11320,2,Chennai Super Kings,Kolkata Knight Riders,1,6,SR Watson,F du Plessis,P Krishna,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
172216,11322,2,Mumbai Indians,Royal Challengers Bangalore,9,1,AS Yadav,Ishan Kishan,P Negi,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
173344,11327,1,Mumbai Indians,Rajasthan Royals,14,6,Q de Kock,HH Pandya,STR Binny,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
174898,11333,2,Kings XI Punjab,Royal Challengers Bangalore,13,1,DA Miller,N Pooran,M Ali,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
175558,11336,2,Rajasthan Royals,Sunrisers Hyderabad,2,6,AM Rahane,L Livingstone,Shakib Al Hasan,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
175689,11337,1,Delhi Capitals,Royal Challengers Bangalore,4,6,S Dhawan,SS Iyer,UT Yadav,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
176028,11338,1,Kolkata Knight Riders,Mumbai Indians,19,8,AD Russell,KD Karthik,JJ Bumrah,0,...,0,1,0,0,1,1,2,NaN,NaN,NaN
177872,11346,2,Kings XI Punjab,Chennai Super Kings,17,6,Mandeep Singh,S Curran,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
178861,11415,1,Mumbai Indians,Chennai Super Kings,5,6,AS Yadav,RG Sharma,SN Thakur,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [ ]:
delivery.shape

(179078, 21)

In [ ]:
matches.shape

(756, 18)

**Filtering Data**

In [ ]:
df=delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

In [ ]:
#Changing total runs to target column so adding +1 in each total_runs value

df['total_runs']=df['total_runs'] + 1

In [ ]:
df=df[df['inning']==1]

In [ ]:
df.rename({'total_runs':'target'},axis=1,inplace=True)

In [ ]:
df.drop('inning',axis=1,inplace=True)

In [ ]:
matches

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [ ]:
df.rename(columns={'match_id':'id'},inplace=True)

In [ ]:
merged_matches=matches.merge(df,on='id')

In [ ]:
merged_matches

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,target
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,208
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,185
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,184
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,164
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,144
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,137
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,172
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,156
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,153

In [ ]:
merged_matches=merged_matches[merged_matches['result']=='normal']

In [ ]:
merged_matches=merged_matches[merged_matches['dl_applied']==0]

In [ ]:
mm=merged_matches

In [ ]:
mm.rename(columns={'id':'match_id'},inplace=True)

In [ ]:
mm['team1']=mm['team1'].str.replace('Delhi Daredevils','Delhi Capitals')

In [ ]:
mm['team2']=mm['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

In [ ]:
mm['team1']=mm['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad ')

In [ ]:
mm['team2']=mm['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad ')

In [ ]:
mm['team1']=mm['team1'].str.strip()

In [ ]:
mm['team2']=mm['team2'].str.strip()

In [ ]:
mm['team1'].value_counts()

team1
Sunrisers Hyderabad            102
Mumbai Indians                 100
Kings XI Punjab                 88
Chennai Super Kings             86
Royal Challengers Bangalore     81
Kolkata Knight Riders           79
Delhi Capitals                  71
Rajasthan Royals                63
Pune Warriors                   20
Gujarat Lions                   13
Rising Pune Supergiant           8
Kochi Tuskers Kerala             7
Rising Pune Supergiants          6
Name: count, dtype: int64

In [ ]:
teams_to_remove = ['Rising Pune Supergiants','Rising Pune Supergiant','Kochi Tuskers Kerala','Pune Warriors','Gujarat Lions']

# Remove rows where 'team2' is in the list
mm = mm[~mm['team2'].isin(teams_to_remove)]

In [ ]:
teams_to_remove = ['Rising Pune Supergiants','Rising Pune Supergiant','Kochi Tuskers Kerala','Pune Warriors','Gujarat Lions']

# Remove rows where 'team1' is in the list
mm = mm[~mm['team1'].isin(teams_to_remove)]

In [ ]:
mm['team1'].value_counts()

team1
Sunrisers Hyderabad            94
Mumbai Indians                 91
Chennai Super Kings            81
Kings XI Punjab                80
Kolkata Knight Riders          72
Royal Challengers Bangalore    72
Delhi Capitals                 65
Rajasthan Royals               60
Name: count, dtype: int64

In [ ]:
mm=mm[['match_id','city','winner','target']]

In [ ]:
delivery=delivery.merge(mm,on='match_id')

In [ ]:
#assigning small variable name for comfort
dl=delivery

In [ ]:
dl=dl[dl['inning']==2]

In [ ]:
dl['current_score']=dl.groupby('match_id')['total_runs'].cumsum()

/tmp/ipython-input-41-2029277757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dl['current_score']=dl.groupby('match_id')['total_runs'].cumsum()

In [ ]:
dl['runs_left']=dl['target']-dl['current_score']

/tmp/ipython-input-42-1616000384.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dl['runs_left']=dl['target']-dl['current_score']

In [ ]:
dl=dl[dl['runs_left']>-6]

In [ ]:
dl['balls_left']=126 - (dl['over']*6 + dl['ball'])

In [ ]:
dl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,total_runs,player_dismissed,dismissal_kind,fielder,city,winner,target,current_score,runs_left,balls_left
125,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,Mandeep Singh,A Nehra,0,...,1,NaN,NaN,NaN,Hyderabad,Sunrisers Hyderabad,208,1,207,119
126,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,CH Gayle,A Nehra,0,...,0,NaN,NaN,NaN,Hyderabad,Sunrisers Hyderabad,208,1,207,118
127,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,CH Gayle,A Nehra,0,...,0,NaN,NaN,NaN,Hyderabad,Sunrisers Hyderabad,208,1,207,117
128,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,CH Gayle,A Nehra,0,...,2,NaN,NaN,NaN,Hyderabad,Sunrisers Hyderabad,208,3,205,116
129,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,CH Gayle,A Nehra,0,...,4,NaN,NaN,NaN,Hyderabad,Sunrisers Hyderabad,208,7,201,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147193,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,1,NaN,NaN,NaN,Hyderabad,Mumbai Indians,153,152,1,4
147194,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,2,NaN,NaN,NaN,Hyderabad,Mumbai Indians,153,154,-1,3
147195,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,1,SR Watson,run out,KH Pandya,Hyderabad,Mumbai Indians,153,155,-2,2
147196,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,2,NaN,NaN,NaN,Hyderabad,Mumbai Indians,153,157,-4,1
147197,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,SN Thakur,lbw,NaN,Hyderabad,Mumbai Indians,153,157,-4,0

In [ ]:
dl['rrr']=dl['runs_left']/(dl['balls_left']/6)

In [ ]:
dl['crr']=dl['current_score']/((120-dl['balls_left'])/6)

In [ ]:
dl['result']='0'

In [ ]:
def result(row):
    return 1 if row['batting_team']==row['winner'] else 0

In [ ]:
dl['result']=dl.apply(result,axis=1)

In [ ]:
dl['player_dismissed']=dl['player_dismissed'].fillna('0')

In [ ]:
dl['player_dismissed']=dl['player_dismissed'].apply(lambda x: x if x=='0' else 1)

In [ ]:
dl['player_dismissed']=dl['player_dismissed'].astype('int')

In [ ]:
wickets=dl.groupby('match_id')['player_dismissed'].cumsum()

In [ ]:
dl['wickets_left']=10-wickets

In [ ]:
pro=dl[['batting_team','bowling_team','city','target','current_score','runs_left','balls_left','wickets_left','rrr','crr','result']]

In [ ]:
pro.dropna(inplace=True)

/tmp/ipython-input-57-2577406078.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pro.dropna(inplace=True)

In [ ]:
pro.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70526 entries, 125 to 147197
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   batting_team   70526 non-null  object
 1   bowling_team   70526 non-null  object
 2   city           70526 non-null  object
 3   target         70526 non-null  int64
 4   current_score  70526 non-null  int64
 5   runs_left      70526 non-null  int64
 6   balls_left     70526 non-null  int64
 7   wickets_left   70526 non-null  int64
 8   rrr            70526 non-null  float64
 9   crr            70526 non-null  float64
 10  result         70526 non-null  int64
dtypes: float64(2), int64(6), object(3)
memory usage: 6.5+ MB

In [ ]:
pro.describe()

/usr/local/lib/python3.11/dist-packages/numpy/_core/_methods.py:52: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

,target,current_score,runs_left,balls_left,wickets_left,rrr,crr,result
count,70526.000000,70526.000000,70526.000000,70526.000000,70526.000000,7.052600e+04,70526.000000,70526.000000
mean,166.888013,73.342994,93.545019,62.719494,7.537617,NaN,7.453918,0.525792
std,29.330790,46.870683,50.024865,33.359689,2.141998,NaN,2.279851,0.499338
min,68.000000,0.000000,-5.000000,-2.000000,0.000000,-inf,0.000000,0.000000
25%,148.000000,34.000000,54.000000,35.000000,6.000000,7.274336e+00,6.272727,0.000000
50%,166.000000,70.000000,93.000000,63.000000,8.000000,9.000000e+00,7.500000,1.000000
75%,186.000000,109.000000,131.000000,92.000000,9.000000,1.108819e+01,8.702027,1.000000
max,251.000000,223.000000,250.000000,119.000000,10.000000,inf,42.000000,1.000000

In [ ]:
pro=pro[pro['balls_left']!=0]

In [ ]:
pro=pro.sample(pro.shape[0])

In [ ]:
pro

,batting_team,bowling_team,city,target,current_score,runs_left,balls_left,wickets_left,rrr,crr,result
7177,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,223,9,214,109,9,11.779817,4.909091,0
109472,Mumbai Indians,Royal Challengers Bangalore,Mumbai,236,181,55,7,4,47.142857,9.610619,0
48660,Mumbai Indians,Royal Challengers Bangalore,Bangalore,141,70,71,65,9,6.553846,7.636364,1
98574,Kings XI Punjab,Kolkata Knight Riders,Kolkata,164,7,157,109,9,8.642202,3.818182,0
78403,Rajasthan Royals,Royal Challengers Bangalore,Jaipur,172,21,151,107,10,8.467290,9.692308,1
...,...,...,...,...,...,...,...,...,...,...,...
51327,Kings XI Punjab,Delhi Daredevils,Delhi,232,155,77,25,6,18.480000,9.789474,0
91686,Royal Challengers Bangalore,Mumbai Indians,Mumbai,188,124,64,31,6,12.387097,8.359551,0
42208,Delhi Daredevils,Kolkata Knight Riders,Kolkata,182,63,119,74,9,9.648649,8.217391,0
82461,Rajasthan Royals,Chennai Super Kings,Jaipur,142,24,118,84,7,8.428571,4.000000,1
60772,Delhi Daredevils,Deccan Chargers,Delhi,158,2,156,116,10,8.068966,3.000000,1

TRAINING THE DATA

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=pro.drop('result',axis=1)
y=pro['result']

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,shuffle=False,test_size=.25)

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(
    transformers=[
        ('ttf1', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
    ],
    remainder='passthrough'
)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [ ]:
pipe=Pipeline([
    ('step1',ct),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [ ]:
#Checking the data before fitting the pipeline
xtrain.isnull().sum()

batting_team     0
bowling_team     0
city             0
target           0
current_score    0
runs_left        0
balls_left       0
wickets_left     0
rrr              0
crr              0
dtype: int64

In [ ]:
xtest.isnull().sum()

batting_team     0
bowling_team     0
city             0
target           0
current_score    0
runs_left        0
balls_left       0
wickets_left     0
rrr              0
crr              0
dtype: int64

In [ ]:
pipe.fit(xtrain,ytrain)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ttf1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [ ]:
prediction=pipe.predict(xtest)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy=accuracy_score(ytest,prediction)

In [ ]:
print('Accuracy of our model is:',accuracy)

Accuracy of our model is: 0.8022872098315885

In [ ]:
pipe.predict_proba(xtest)[10]

array([0.95, 0.05])

**Random Forest Algorithm**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [ ]:
pipe=Pipeline([
    ('step1',ct),
    ('step2',rf)
])

In [ ]:
pipe.fit(xtrain,ytrain)

/usr/local/lib/python3.11/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ttf1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', RandomForestClassifier())])

In [ ]:
prediction2=pipe.predict(xtest)

In [ ]:
accuracy2=accuracy_score(ytest,prediction2)

In [ ]:
print('The accuracy of Random forest is:',accuracy2)

The accuracy of Random forest is: 0.9982931269913519